name: Deploy Flask Application

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Flask Application (for development or testing)
      - name: Run Flask App
        env:
          FLASK_APP: app.py  # Adjust this to the main file of your Flask app
          FLASK_ENV: development
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &

      # Step 5: Keep the application running
      - name: Keep the Action Alive
        run: sleep infinity
